version: "3"
services:
  postgres:
    image: "postgres"
    container_name: "postgres"
    environment:
      - POSTGRES_USER=ivan
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=codeyourfuture
    ports:
      - "54320:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data